name: build x86
on: [push]
jobs:
  x86:
    runs-on: ubuntu-rolling
    steps:
      - run: apt-get update
      - run: apt-get install -y git cmake nodejs g++-mingw-w64-i686 gnu-efi
      - run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-8`" >> $GITHUB_ENV
      - run: git clone --recurse-submodules ${{ github.server_url }}/${{ github.repository }} ${SHORT_SHA}
      - run: cd ${SHORT_SHA} && git checkout ${{ github.sha }}
      - run: mkdir -p install/debug/drivers && mkdir -p install/drivers
      - run: |
          cmake -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_TOOLCHAIN_FILE=mingw-x86.cmake \
            -S ${SHORT_SHA} -B debug-work && \
          cmake --build debug-work --parallel `nproc` && \
          cp debug-work/quibble.efi install/debug/ &&
          cp debug-work/btrfs/btrfs.efi install/debug/drivers/ &&
          cp debug-work/ntfs/ntfs.efi install/debug/drivers/
      - run: |
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_TOOLCHAIN_FILE=mingw-x86.cmake \
            -S ${SHORT_SHA} -B release-work && \
          cmake --build release-work --parallel `nproc` && \
          cp release-work/quibble.efi install/ &&
          cp release-work/btrfs/btrfs.efi install/drivers/ &&
          cp release-work/ntfs/ntfs.efi install/drivers/
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          overwrite: true
          path: |
            install
